language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
script:
  - npm build
deploy:
  provider: npm
  email: hello@azinasili.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
